# Generated by Django 3.2.4 on 2021-07-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincorps_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accounts', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=200)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
            ],
        ),
    ]
