# Generated by Django 3.2.4 on 2021-07-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincorps_accounts', '0003_auto_20210716_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_ledger',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='general_ledger',
            name='debit',
            field=models.FloatField(default=0.0),
        ),
    ]
