# Generated by Django 3.2.4 on 2021-07-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincorps_accounts', '0004_auto_20210716_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_ledger',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='general_ledger',
            name='debit',
            field=models.FloatField(),
        ),
    ]
