# Generated by Django 3.2.4 on 2021-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincorps_accounts', '0005_auto_20210716_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_ledger',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='general_ledger',
            name='debit',
            field=models.FloatField(null=True),
        ),
    ]
